# 井号开头代表注释
# 添加的格式为 名称: 地址
# 例如：
少数派: https://sspai.com/tag/iOS
GitHub: https://github.com/AlanLang
Blog: http://www.langwenda.cn/
mail: https://exmail.qq.com/cgi-bin/loginpage?t=dm_loginpage&dmtype=bizmail&s=session_timeout
图床: http://jiantuku.com/#/
mes: C:\Users\alan2\iCloudDrive\Documents\我的项目\2018年1月16日 Web端开发框架搭建
下载: D:\下载
插件目录: C:\Users\alan2\AppData\Local\Wox\app-1.3.424\Plugins\wox.plugin.marks